name: 米游社日历更新

# 控制时机
on:
  # push 时
  push:
    branches: [ "main" ]
    
  # 定时器
  schedule:
    - cron: '0,30 3-13 * * *'

  # 手动
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 取当前版本
      - name: Checkout
        uses: actions/checkout@v4
      - name: 配置 pages
        uses: actions/configure-pages@v5
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # 拿数据
      - run: node fetch-calendar.cjs
      # 上传要用的部分用于 pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 发布 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
