name: 米游社日历更新

# 控制时机
on:
  # push 时
  push:
    branches: [ "main" ]
    
  # 定时器
  schedule:
    - cron: '0,30 3-13 * * *'

  # 手动
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      success: ${{ steps.file_check.outputs.exists }}
    steps:
      # 取当前版本
      - name: Checkout
        uses: actions/checkout@v4
      - name: 配置 pages
        uses: actions/configure-pages@v5
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # 拿数据
      - name: 查询并合并数据
        run: node fetch-calendar.cjs
        continue-on-error: true
      - name: 检查
        id: file_check
        run: |
          if [ -f "miyoushe-calendar.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      # 上传要用的部分用于 pages
      - name: 上传 artifact
        if: steps.file_check.outputs.exists == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.success == 'true'
    steps:
      - name: 发布 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
